### $Id: libcdio.spec.in,v 1.2 2006/03/28 14:11:56 rocky Exp $
### autogenerated---edit *.spec.in

%define name    libcdio
%define ver     0.92
%define rel     0

Name:           %{name}
Summary:        CD-ROM access library
Version:        %{ver}
Release:        %{rel}
License:        GPL
Group:          Development/Libraries
URL:            http://www.gnu.org/software/libcdio/

Source0:        %{name}-%{version}.tar.gz

%description
The libcdio package contains a library for CD-ROM and CD image
access. Applications wishing to be oblivious of the OS- and
device-dependent properties of a CD-ROM or of the specific details of
various CD-image formats may benefit from using this library.

A library for working with ISO-9660 filesystems libiso9660 is
included. A generic interface for issuing MMC (multimedia commands) is
also part of the libcdio library.

%package devel
Summary:        libcdio development package
Group:          Development/Libraries
Requires:       %{name} = %{version}-%{release}

%description devel
libcdio development package

%package -n cdinfo
Summary:        cd-info
Group:          Applications/Multimedia
Requires:       %{name} = %{version}-%{release}
#Requires:       libcddb
#BuildRequires:  libcddb-devel

%description -n cdinfo

cd-info prints various information about a CD or CD image, analyzes
and gives information about each of the tracks, and tries to detect
the type of CD (e.g. VCD, Audio CD, PhotoCD, a bootable CD, etc.). For
audio CD's more information is given if libcddb is installed. For
Video CD's more information is given if the libvcdinfo library is
installed.

%prep
%setup -q %{name}-%{version}

%build
%configure am_cv_func_iconv_works=yes

make %{?_smp_mflags}

%install
%makeinstall
rm -rf ${RPM_BUILD_ROOT}/%{_mandir}

%post
/sbin/ldconfig

%postun
/sbin/ldconfig

%files
%defattr(-,root,root)
%doc AUTHORS INSTALL NEWS THANKS TODO
%{_libdir}/lib*.so.*

%files devel
%defattr(-, root, root)
%doc ChangeLog COPYING README
%{_libdir}/lib*.so
%{_libdir}/*.*a
%{_includedir}/cdio/*
%{_includedir}/cdio++/*
%{_infodir}/*
%{_libdir}/pkgconfig/*.pc

%files -n cdinfo
%defattr(-,root,root)
%{_bindir}/*
